### ISSUE TITLE
Community-wide estimation maximal microbial growth rate using 16S

### ISSUE THREAD

**Issue by danieldavilaaleman** [jlw-ecoevo/gRodon2#6]
Hello,

My name is Daniel Davila, and I want to thank you for sharing gRodon2. I want to estimate the maximal microbial growth rate of my microbial community, but I only have 16S data. I used EGGO blast DB to use the close relative to infer the growth rate of the microbial community, but I want it to correct for relative abundance. What would you suggest to correct the maximal microbial growth rate for relative abundance?

Thank you very much, and looking forward to hearing from you!
Best,
Daniel Davila

**Comment by jlw-ecoevo** [comment]
Hi! [Paprica](https://github.com/bowmanjeffs/paprica) now has implemented gRodon growth predictions and is probably the easiest option to do what you want. Otherwise you could assign a growth rate to each ASV/OTU using BLAST as you did and then take the weighted average for each sample using your relative abundances for each ASV/OTU.

**Comment by danieldavilaaleman** [comment]
Thank you very much for your suggestions and help!!!
